// Generated by :backend:worker:shared:generateBakedConfig from `terraform output`.
// Do not edit by hand — re-run the task after re-provisioning and commit the diff.
package software.medusa.farm.worker

object BakedConfig {
  const val TEMPORAL_ADDRESS = "us-east-1.aws.api.temporal.io:7233"
  const val TEMPORAL_NAMESPACE = "farm.kr9zt"
  const val TEMPORAL_KEY_PROJECT = "ms-farm-shared-c83577a8"
}
