plugins {
  alias(libs.plugins.kotlin.jvm)
  alias(libs.plugins.kotlin.serialization)
  alias(libs.plugins.sqldelight)
  `java-library`
}

dependencies {
  // api() (not implementation) so consumers get Hikari's transitive slf4j-api at compile time.
  api(libs.hikaricp)
  api(libs.kotlinx.coroutines.core)
  // The agent-run action log is modeled as @Serializable types stored as JSON on session_run.
  implementation(libs.kotlinx.serialization.json)
  // api() because WorkflowServiceAuthConfig exposes WorkflowServiceStubsOptions.Builder in its
  // public signature.
  api(libs.temporal.sdk)
  implementation(libs.flyway.core)
  implementation(libs.sqldelight.jdbc.driver)
  runtimeOnly(libs.flyway.database.postgresql)
  runtimeOnly(libs.postgresql)

  testImplementation(libs.kotlin.test)
}

sqldelight {
  databases {
    create("FarmDatabase") {
      packageName.set("software.medusa.farm.shared.db")
      dialect(libs.sqldelight.postgresql.dialect)
    }
  }
}

base { archivesName = "backend-shared" }

// The migrations and the queries run against them are only really checked by a real database: the
// .sq files carry a hand-copied mirror of the schema that SQLDelight validates queries against, and
// nothing but a live Postgres says whether that mirror still matches what Flyway builds. Needs
// Docker, so it stays out of the `test`/`check` lifecycle and runs via the `integrationTest` task.
val integrationTest by sourceSets.creating {
  compileClasspath += sourceSets["main"].output
  runtimeClasspath += sourceSets["main"].output
}

configurations["integrationTestImplementation"].extendsFrom(configurations["testImplementation"])

configurations["integrationTestRuntimeOnly"].extendsFrom(configurations["testRuntimeOnly"])

// Named rather than typed: the configuration only exists once the source set above is created.
dependencies { "integrationTestImplementation"(libs.testcontainers.postgresql) }

tasks.register<Test>("integrationTest") {
  description = "Runs the migrations and the stores against a real Postgres."
  group = "verification"
  testClassesDirs = integrationTest.output.classesDirs
  classpath = integrationTest.runtimeClasspath
  useJUnitPlatform()
  // Starts a container; nothing about that is a task input, so never up to date.
  outputs.upToDateWhen { false }
  testLogging {
    events("passed", "skipped", "failed")
    exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
  }
}

// Regenerate the baked config from infra/config/config.json — the shared Temporal Cloud coordinates
// (consumed by both the API and the worker) and the per-environment GitHub App client id (baked
// into
// the worker runner). Run deliberately after editing the config and commit the result; it is NOT
// wired into the build, so a clean checkout compiles the committed files with no terraform or cloud
// access.
tasks.register("generateBakedConfig") {
  group = "build setup"
  description = "Regenerate the baked config from infra/config/config.json."
  doLast {
    val configFile = rootDir.resolve("infra/config/config.json")

    @Suppress("UNCHECKED_CAST")
    val config = groovy.json.JsonSlurper().parse(configFile) as Map<String, Any?>

    @Suppress("UNCHECKED_CAST") val temporal = config["temporal"] as Map<String, Any?>

    fun temporal(key: String): String =
        temporal[key]?.toString() ?: error("config.json is missing temporal.$key")

    @Suppress("UNCHECKED_CAST") val secrets = config["secrets"] as Map<String, Any?>

    fun secret(key: String): String =
        secrets[key]?.toString() ?: error("config.json is missing secrets.$key")

    val bakedConfig = file("src/main/kotlin/software/medusa/farm/shared/BakedConfig.kt")
    bakedConfig.writeText(
        """
        |// Generated by :backend:shared:generateBakedConfig from infra/config/config.json.
        |// Do not edit by hand — re-run the task after editing the config and commit the diff.
        |package software.medusa.farm.shared
        |
        |object BakedConfig {
        |  const val TEMPORAL_ADDRESS = "${temporal("address")}"
        |  const val TEMPORAL_NAMESPACE = "${temporal("namespace")}"
        |  const val TEMPORAL_KEY_PROJECT = "${temporal("key_project")}"
        |
        |  const val DATABASE_URL_SECRET_ID = "${secret("database_url")}"
        |  const val GITHUB_APP_PEM_SECRET_ID = "${secret("github_app_pem")}"
        |  const val OPENROUTER_API_KEY_SECRET_ID = "${secret("openrouter_api_key")}"
        |  const val TEMPORAL_API_KEY_SECRET_ID = "${secret("temporal_api_key")}"
        |}
        |
        """
            .trimMargin()
    )
    logger.lifecycle("Wrote $bakedConfig")

    @Suppress("UNCHECKED_CAST")
    val environments = config["environments"] as Map<String, Map<String, Any?>>

    val clientIdConsts =
        environments.entries
            .sortedBy { it.key }
            .joinToString("\n") { (env, envConfig) ->
              val clientId =
                  envConfig["github_app_client_id"]
                      ?: error("config.json is missing environments.$env.github_app_client_id")
              """  const val ${env.uppercase()} = "$clientId""""
            }

    val clientIds = file("src/main/kotlin/software/medusa/farm/shared/BakedGitHubAppClientIds.kt")
    clientIds.writeText(
        """
        |// Generated by :backend:shared:generateBakedConfig from infra/config/config.json.
        |// Do not edit by hand — re-run the task after editing the config and commit the diff.
        |package software.medusa.farm.shared
        |
        |object BakedGitHubAppClientIds {
        |$clientIdConsts
        |}
        |
        """
            .trimMargin()
    )
    logger.lifecycle("Wrote $clientIds")
  }
}
