plugins {
  alias(libs.plugins.kotlin.jvm)
  alias(libs.plugins.sqldelight)
  `java-library`
}

dependencies {
  // api() (not implementation) so consumers get Hikari's transitive slf4j-api at compile time.
  api(libs.hikaricp)
  api(libs.kotlinx.coroutines.core)
  // api() because WorkflowServiceAuthConfig exposes WorkflowServiceStubsOptions.Builder in its
  // public signature; the API's starter and the worker's host consume it.
  api(libs.temporal.sdk)
  implementation(libs.flyway.core)
  implementation(libs.sqldelight.jdbc.driver)
  runtimeOnly(libs.flyway.database.postgresql)
  runtimeOnly(libs.postgresql)

  testImplementation(libs.kotlin.test)
}

sqldelight {
  databases {
    create("FarmDatabase") {
      packageName.set("software.medusa.farm.shared.db")
      dialect(libs.sqldelight.postgresql.dialect)
    }
  }
}

base { archivesName = "backend-shared" }

// Regenerate BakedConfig.kt from infra/temporal's terraform outputs — the non-secret Temporal Cloud
// coordinates (consumed by both the API and the worker). Run deliberately after re-provisioning and
// commit the result; it is NOT wired into the build, so a clean checkout compiles the committed
// file
// with no terraform or cloud access.
tasks.register("generateBakedConfig") {
  group = "build setup"
  description = "Regenerate BakedConfig.kt from infra/temporal terraform outputs."
  doLast {
    val tfDir = rootDir.resolve("infra/temporal").absolutePath
    fun output(name: String): String {
      val process =
          ProcessBuilder("terraform", "-chdir=$tfDir", "output", "-raw", name)
              .redirectError(ProcessBuilder.Redirect.INHERIT)
              .start()
      val value = process.inputStream.bufferedReader().readText().trim()
      check(process.waitFor() == 0) {
        "terraform output -raw $name failed — is infra/temporal applied and initialized?"
      }
      return value
    }
    val address = output("grpc_address")
    val namespace = output("namespace_id")
    val keyProject = output("shared_project_id")
    val target = file("src/main/kotlin/software/medusa/farm/shared/BakedConfig.kt")
    target.writeText(
        """
        |// Generated by :backend:shared:generateBakedConfig from `terraform output`.
        |// Do not edit by hand — re-run the task after re-provisioning and commit the diff.
        |package software.medusa.farm.shared
        |
        |object BakedConfig {
        |  const val TEMPORAL_ADDRESS = "$address"
        |  const val TEMPORAL_NAMESPACE = "$namespace"
        |  const val TEMPORAL_KEY_PROJECT = "$keyProject"
        |}
        |
        """
            .trimMargin()
    )
    logger.lifecycle("Wrote $target")
  }
}
