plugins { alias(libs.plugins.kotlin.jvm) }

dependencies {
  implementation(project(":backend:shared"))
  implementation(libs.kotlinx.coroutines.core)
  implementation(libs.temporal.sdk)

  testImplementation(libs.kotlin.test)
  testImplementation(libs.temporal.testing)
}

kotlin { jvmToolchain(21) }

// Distinct jar name so the proper/runner distributions don't collide with :backend:shared's
// shared.jar (both projects are named "shared").
base { archivesName = "backend-worker-shared" }

// Regenerate BakedConfig.kt from infra/temporal's terraform outputs — the non-secret Temporal Cloud
// coordinates. Run deliberately after re-provisioning and commit the result; it is NOT wired into
// the
// build, so a clean checkout compiles the committed file with no terraform or cloud access.
tasks.register("generateBakedConfig") {
  group = "build setup"
  description = "Regenerate BakedConfig.kt from infra/temporal terraform outputs."
  doLast {
    val tfDir = rootDir.resolve("infra/temporal").absolutePath
    fun output(name: String): String {
      val process =
          ProcessBuilder("terraform", "-chdir=$tfDir", "output", "-raw", name)
              .redirectError(ProcessBuilder.Redirect.INHERIT)
              .start()
      val value = process.inputStream.bufferedReader().readText().trim()
      check(process.waitFor() == 0) {
        "terraform output -raw $name failed — is infra/temporal applied and initialized?"
      }
      return value
    }
    val address = output("grpc_address")
    val namespace = output("namespace_id")
    val target = file("src/main/kotlin/software/medusa/farm/worker/BakedConfig.kt")
    target.writeText(
        """
        |// Generated by :backend:worker:shared:generateBakedConfig from `terraform output`.
        |// Do not edit by hand — re-run the task after re-provisioning and commit the diff.
        |package software.medusa.farm.worker
        |
        |object BakedConfig {
        |  const val TEMPORAL_ADDRESS = "$address"
        |  const val TEMPORAL_NAMESPACE = "$namespace"
        |}
        |
        """
            .trimMargin()
    )
    logger.lifecycle("Wrote $target")
  }
}
