// Generated by :backend:shared:generateBakedConfig from infra/config/config.json.
// Do not edit by hand — re-run the task after editing the config and commit the diff.
package software.medusa.farm.shared

object BakedGitHubAppClientIds {
  const val PROD = "Iv23liqulmJ6FLb48pE5"
  const val STAGING = "Iv23liUa4I1Mh1CZwWaH"
}
